ALTER TYPE "AuthAuditEvent" ADD VALUE IF NOT EXISTS 'EXERCISE_CREATED';
ALTER TYPE "AuthAuditEvent" ADD VALUE IF NOT EXISTS 'EXERCISE_UPDATED';
ALTER TYPE "AuthAuditEvent" ADD VALUE IF NOT EXISTS 'EXERCISE_DUPLICATED';
ALTER TYPE "AuthAuditEvent" ADD VALUE IF NOT EXISTS 'EXERCISE_DEACTIVATED';
ALTER TYPE "AuthAuditEvent" ADD VALUE IF NOT EXISTS 'EXERCISE_GLOBAL_EDIT_DENIED';
ALTER TYPE "AuthAuditEvent" ADD VALUE IF NOT EXISTS 'EXERCISE_ACCESS_DENIED';

ALTER TYPE "ExerciseCategory" ADD VALUE IF NOT EXISTS 'CLEAN_AND_JERK';
ALTER TYPE "ExerciseCategory" ADD VALUE IF NOT EXISTS 'DEADLIFT';
ALTER TYPE "ExerciseCategory" ADD VALUE IF NOT EXISTS 'MOBILITY';
ALTER TYPE "ExerciseCategory" ADD VALUE IF NOT EXISTS 'GENERAL_WARMUP';
