ALTER TYPE "AuthAuditEvent" ADD VALUE IF NOT EXISTS 'TRAINING_CORE_PRESCRIPTION_CREATED';
ALTER TYPE "AuthAuditEvent" ADD VALUE IF NOT EXISTS 'TRAINING_ACCESSORY_PRESCRIPTION_CREATED';
ALTER TYPE "AuthAuditEvent" ADD VALUE IF NOT EXISTS 'PERSONAL_RECORD_UPDATE_CONFIRMED';
ALTER TYPE "AuthAuditEvent" ADD VALUE IF NOT EXISTS 'PERSONAL_RECORD_UPDATE_DECLINED';

ALTER TABLE "training_sets" ADD COLUMN "pr_candidate_declined_weight" DECIMAL(6,2);
